-- MySQL Script generated by MySQL Workbench
-- Tue May  4 09:44:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schronisko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schronisko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schronisko` DEFAULT CHARACTER SET utf8 ;
USE `schronisko` ;

-- -----------------------------------------------------
-- Table `schronisko`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schronisko`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `login` VARCHAR(60) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `uprawnienia` ENUM("admin", "opiekun") NOT NULL,
  `data_dolaczenia` DATE NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schronisko`.`animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schronisko`.`animals` (
  `animal_id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nr_klatki` INT NULL,
  `opiekun` INT NULL,
  `rodzaj` VARCHAR(45) NULL,
  `plec` ENUM("samiec", "samica") NULL,
  `wykastrowany` ENUM("tak", "nie") NULL,
  `nr_chipa` INT NULL,
  `szacowany_wiek` INT NULL COMMENT 'wiek liczy się w latach ziemskich',
  `data_dodania` DATE NULL,
  `stan` MEDIUMTEXT NULL,
  PRIMARY KEY (`animal_id`),
  INDEX `fk_animals_users_idx` (`opiekun` ASC),
  UNIQUE INDEX `nr chipa_UNIQUE` (`nr_chipa` ASC),
  UNIQUE INDEX `animal_id_UNIQUE` (`animal_id` ASC),
  CONSTRAINT `fk_animals_users`
    FOREIGN KEY (`opiekun`)
    REFERENCES `schronisko`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
